services:
  - type: web
    name: pothole-detector-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn Server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: MODEL_PATH
        value: best.pt
      - key: YOLO_CONFIG_DIR
        value: /tmp/Ultralytics
